module.exports.GAME_STATES = {
  PRESTART: 'PRESTART',
  PLAYER_NUMBER: 'PLAYER_NUMBER',
  PLAYER_NAME: 'PLAYER_NAME',
  PLAYING: 'PLAYING',
  STOPPED: 'STOPPED',
  GAME_OVER: 'GAME_OVER',
  HELP: 'HELP',
};
