module.exports.GAME_STATES = {
  HELP: 'HELP',
  PLAYING: 'PLAYING',
  PRESTART: 'PRESTART',
  PLAYER_NUMBER: 'PLAYER_NUMBER',
  PLAYER_NAME: 'PLAYER_NAME',
  START: 'START',
  GAME_OVER: 'GAME_OVER',
};
